# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/kubernetes-sigs/cri-tools
%global goipath         github.com/kubernetes-sigs/cri-tools
Version:                1.27.1

%gometa

%global common_description %{expand:
CLI and validation tools for Kubelet Container Runtime Interface (CRI) .}

%global golicenses      LICENSE hack/repo-infra/LICENSE
%global godocs          docs CHANGELOG.md CONTRIBUTING.md README.md\\\
                        RELEASE.md code-of-conduct.md hack/repo-\\\
                        infra/README.md hack/repo-infra/verify/README.md\\\
                        hack/repo-\\\
                        infra/verify/boilerplate/boilerplate.Dockerfile.txt\\\
                        hack/repo-\\\
                        infra/verify/boilerplate/boilerplate.Makefile.txt\\\
                        hack/repo-infra/verify/boilerplate/boilerplate.go.txt\\\
                        hack/repo-infra/verify/boilerplate/boilerplate.py.txt\\\
                        hack/repo-infra/verify/boilerplate/boilerplate.sh.txt

Name:           %{goname}
Release:        1%{?dist}
Summary:        CLI and validation tools for Kubelet Container Runtime Interface (CRI) 

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE hack/repo-infra/LICENSE
%doc docs CHANGELOG.md CONTRIBUTING.md README.md RELEASE.md code-of-conduct.md
%doc hack/repo-infra/README.md hack/repo-infra/verify/README.md
%doc hack/repo-infra/verify/boilerplate/boilerplate.Dockerfile.txt
%doc hack/repo-infra/verify/boilerplate/boilerplate.Makefile.txt
%doc hack/repo-infra/verify/boilerplate/boilerplate.go.txt
%doc hack/repo-infra/verify/boilerplate/boilerplate.py.txt
%doc hack/repo-infra/verify/boilerplate/boilerplate.sh.txt
%{_bindir}/*

%gopkgfiles

%changelog
* Sat May 07 2022 Dudecake <coen_koomen@hotmail.com> - 1.25.0-1
- Initial package
